#!/bin/bash

c() {
	awk 'BEGIN{printf "%.3f\n", ('$1')}' | sed s/,/\./
}

export DISPLAY=:0
outp=$(xrandr | grep " con" | awk '{print $1}')
if [ $# -ne 0 ]; then
	case $1 in
		--dpkg-i | -i )
			sudo apt install espeak beep -y
			if [ ! -d /home/$USER/bin ]; then mkdir ~/bin; fi
			if [ ! -f /home/$USER/bin/yeet ]; then
				pth=$( cd "$(dirname "$0")" > /dev/null 2>&1 ; pwd -P )
				cp $pth/yeet ~/bin/
				chmod u+x ~/bin/yeet
			fi
			if [ $(echo $PATH | grep "~/bin/" | wc -l) -eq 0 ]; then echo "Ajouter au \$PATH : PATH=\"\$PATH:~/bin/\""; fi
			;;
		--beepscreen | -s )
			volume=0; if [ $# -gt 1 ];then volume=$2; fi
			phrase=""; if [ $# -gt 2 ];then phrase=$3; fi
			nb=1; if [ $# -gt 3 ];then nb=$4; fi
			lbeep=0; if [ $# -gt 4 ];then lbeep=$5; fi
			fmin=300; if [ $# -gt 5 ];then fmin=$6; fi
			fmax=500; if [ $# -gt 6 ];then fmax=$7; fi
			if [ $lbeep -gt 0]; then sudo echo; fi
			if [ $phrase != "" ];then
				amixer sset 'Master' unmute 1>/dev/null
				amixer sset 'Master' $volume% 1>/dev/null
				espeak "$phrase"
			fi
			for i in $(seq 1 $nb); do
				xrandr --output $outp --gamma 0.$((RANDOM%9+1)):0.$((RANDOM%9+1)):0.$((RANDOM%9+1))
				if [ $lbeep -gt 0 ]; then sudo env -i beep -l $lbeep -f $((RANDOM%($fmax-$fmin)+$fmin)); fi
			done
			;;
		--brightness | -b )
			nb=1; if [ $# -gt 1 ];then nb=$2; fi
			plage=100; if [ $# -gt 2 ];then plage=$3; fi
			min=0; if [ $# -gt 3 ];then min=$4; fi
			max=1; if [ $# -gt 4 ];then max=$5; fi
			sl=0; if [ $# -gt 5 ];then sl=$6; fi
			for n in $(seq 1 $nb); do
				for i in $(seq 1 $plage | sort -nr); do
					xrandr --output $outp --brightness $(c "$min+$i/($plage)*($max-$min)")
					if [ $sl -gt 0 ]; then sleep $sl; fi
				done
				for i in $(seq 1 $plage); do
					xrandr --output $outp --brightness $(c "$min+$i/($plage)*($max-$min)")
					if [ $sl -gt 0 ]; then sleep $sl; fi
				done
			done
			;;
		--colors | -c )
			nb=1; if [ $# -gt 1 ];then nb=$2; fi
			plage=100; if [ $# -gt 2 ];then plage=$3; fi
			for n in $(seq 1 $nb); do
				for i in $(seq 1 $plage | sort -nr); do xrandr --output $outp --gamma $(c "$i/$plage"):1:1; done
				for i in $(seq 1 $plage); do xrandr --output $outp --gamma $(c "$i/$plage"):1:1; done
				for i in $(seq 1 $plage | sort -nr); do xrandr --output $outp --gamma 1:$(c "$i/$plage"):1; done
				for i in $(seq 1 $plage); do xrandr --output $outp --gamma 1:$(c "$i/$plage"):1; done
				for i in $(seq 1 $plage | sort -nr); do xrandr --output $outp --gamma 1:1:$(c "$i/$plage"); done
				for i in $(seq 1 $plage); do xrandr --output $outp --gamma 1:1:$(c "$i/$plage"); done
			done
			;;
		--keycolors | -k )
			br=0; if [ $# -gt 2 ];then br=$3; fi
			bp=0; if [ $# -gt 3 ];then bp=$4; fi
			if [ $bp -eq 1 ];then sudo echo; fi
			while true; do
				read -rsn1 input
				if [ "$input" != "" ];then
					if [ $br -eq 1 ];then xrandr --output $outp --gamma 0.$((RANDOM%9+1)):0.$((RANDOM%9+1)):0.$((RANDOM%9+1)) --brightness 0.$((RANDOM%9+1))
					else xrandr --output $outp --gamma 0.$((RANDOM%9+1)):0.$((RANDOM%9+1)):0.$((RANDOM%9+1)); fi
					if [ $bp -eq 1 ];then sudo env -i beep -l 50 -f $((RANDOM%($fmax-$fmin)+$fmin)); fi
				fi
			done
			;;
		--windows | -w )
			url=https://pbs.twimg.com/profile_images/1142134932799741952/rlSQOnp4.jpg; if [ $# -gt 1 ];then url=$2; fi
			nb=1; if [ $# -gt 2 ];then nb=$3; fi
			if [ $# -gt 3 ];then for i in $(seq 1 $nb); do firefox --new --tab $url; done
			else for i in $(seq 1 $nb); do firefox --new-window $url; done; fi
			;;
		--piano | -p )
			declare -A idx=(['q']=0 ['s']=1 ['d']=2 ['f']=3 ['g']=4 ['h']=5 ['j']=6 ['k']=7 ['l']=8 ['m']=9)
			declare -a octave0=('16' '17' '18' '19' '20' '21' '23' '24' '25' '27' '29' '30')
			declare -a octave1=('32' '34' '36' '38' '41' '43' '46' '49' '51' '55' '58' '61')
			declare -a octave2=('65' '69' '73' '77' '82' '87' '92' '98' '103' '110' '116' '123')
			declare -a octave3=('130' '138' '146' '155' '164' '174' '185' '196' '207' '220' '233' '246')
			declare -a octave4=('261' '277' '293' '311' '329' '349' '369' '392' '415' '440' '466' '493')
			declare -a octave5=('523' '554' '587' '622' '659' '698' '739' '783' '830' '880' '932' '987')
			declare -a octave6=('1046' '1108' '1174' '1244' '1318' '1396' '1479' '1567' '1661' '1760' '1864' '1975')
			declare -a octave7=('2093' '2217' '2349' '2489' '2637' '2793' '2959' '3135' '3322' '3520' '3729' '3951')
			declare -a octave8=('4186' '4434' '4698' '4978' '5274' '5587' '5919' '6271' '6644' '7040' '7458' '7902')
			declare -a octave9=('8372' '8869' '9397' '9956' '10548' '11175' '11839' '12543' '13289' '14080' '14917' '15804')
			declare -a octave10=('16744' '17739' '18794' '19912' '21096' '22350' '23679' '25087' '26579' '28160' '29834' '31608')
			((octave=0))
			echo "Octave choisi : 0"
			while true; do
			read -rsn1 input
			if [ "$input" != "" ];then
				if [ "$input" == "0" -o "$input" == "1" -o "$input" == "2" -o "$input" == "3" -o "$input" == "4" -o "$input" == "5" -o "$input" == "6" -o "$input" == "7" -o "$input" == "8" -o "$input" == "9" ];then ((octave=$input));echo "Changement d'octave : $octave"
				else eval 'beep -l 50 -f ${octave'$octave'[${idx[$input]}]} &'; fi
			fi
			done
			;;
		--abouibouiboui | -a )
			while true; do
				read -rsn1 input
				if [ "$input" == "a" ];then espeak -v fr "a"; fi
				if [ "$input" == "b" ];then espeak -v fr "boui"; fi
			done
			;;
		--espeak-key | -e )
			while true; do
				read -rsn1 input
				if [ "$input" != "" ]; then espeak "$input"; fi
			done
			;;
		--move-screen | -m )
			while true; do
				read -rsn1 input
				case $input in
					"z" ) xrandr -o normal;;
					"q" ) xrandr -o left;;
					"s" ) xrandr -o inverted;;
					"d" ) xrandr -o right;;
				esac
				if [ "$input" != "" ]; then echo "$input"; fi
			done
			;;
	esac
else echo "Usage of yeet : bash yeet.sh OPTION...
  -i | --dpkg-i
  -s | --beepscreen [volume] [phrase] [nb] [longueur beep] [freq min] [freq max]
  -b | --brightness [nb] [plage] [min] [max] [sleep]
  -c | --colors [nb] [plage]
  -k | --keycolors [brightness] [beep]
  -w | --windows [url] [nb] [tab]
  -p | --piano
  -a | --abouibouiboui
  -e | --espeak-key
  -m | --move-screen
Exemples :
$ yeet -s 60 \"pikatchu, attak eclair\" 3 20 300 2000"
fi
xrandr --output $outp --gamma 1:1:1 --brightness 1 -o normal
